[package]
name = "honeyos-networking"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.14.5"
uuid = "1.8.0"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = [
    "Window",
    "Request",
    "RequestInit",
    "Response",
] }
